### PR TITLE
[WIP] Metascraper analysis and insertion for Metaphor replacement

### PR DESCRIPTION
**Pull request by mbomfim33**
This is the initial commit so I may start working on integrating the Embed-API to use Metascraper. I've made a separate branch to work on this, just to ensure nothing goes south.

### CODE REVIEW

**Comment by roschaefer** [comment]
@MarcoBomfim I wanted to review your work on Metascraper, could you push it?

**Comment by roschaefer** [comment]
@MarcoBomfim we have several dependency updates in this repo. If you're working on it, could you check if `yarn upgrade` breaks the expected behaviour?

**Comment by MarcoBomfim** [comment]
Hey, @roschaefer! Unfortunately last week was a very busy one. I'm planning on dedicating tonight, and Wednesday at night to work both on the upgrade, as well as on the Yarn issues. I'll keep you updated, but if someone else want's to dig into this, feel free to commit as well

**Comment by roschaefer** [comment]
Yes! Excellent.

Did you allowed "maintainers can send updates to this PR" when opening this PR? It's a check mark and it is set by default.

A maintainer is a Github user with write permissions to this repository. We can send commits to `MarcoBomfim:mbomfim-metascraper-bump`. All other members have to ask you for write permissions.

**Comment by roschaefer** [comment]
@MarcoBomfim also please do
```sh
git fetch origin
git merge origin/master
``` 
in order to update your branch. I changed `docker-compose.yml` and `travis.yml`.

**Comment by MarcoBomfim** [comment]
@roschaefer The checkbox is marked, and the PR is up-to-date. Will commit any changes made later on, unfortunately (or fortunately), it has been a very very very busy week. Thanks for the patience though.

**Comment by roschaefer** [comment]
@MarcoBomfim if you want to learn some advanced git usage:

Given that your feature branch is not too far off from the master branch (unlikely to have conflicts) and you did not push your commits to upstream yet. In that case you can keep a linear git history with:
```sh
git fetch origin
git rebase origin/master
```

If you run into many conflicts you can simply `git rebase --abort` and fall back to an all-in-one `git merge origin/master`.

If you rebased but you pushed the previous commits to upstream, you must `git push origin your_feature_branch --force` to overwrite the upstream branch. This is going to remove commits and you have to tell all your team members about it.

**Comment by appinteractive** [comment]
`git push — force` opens Pandora’s case. You should avoid it where possible! It’s the last resort.

**Comment by roschaefer** [comment]
Yeah :laughing: it might get confusing once you overwrite a branch for the first time. You should know the git topology very well. I suggest to a) learn it with a GUI that has a strong focus on the git graph topology, e.g. Gitkraken and b) maybe use a fork at first. Nothing is going to happen if you push to a fork. There is also the `git reflog` for emergencies.

**Comment by MarcoBomfim** [comment]
Hey team, 

Metascraper is already returning the metadata with this latest commit. I've downloaded Gitkraken to try it out since I'm kinda noob on Git still and wasn't able to rebase on origin. Should I do this on my Master? Since I'm currently working on a branch? 

@roschaefer and @appinteractive, I'll study the code later on as well to understand all the conditionals that are left on the embeds.class.js, thanks a lot for being so proactive in helping out!

**Comment by roschaefer** [comment]
@MarcoBomfim maybe the box of pandora is to mention [rebase vs. merge](https://www.atlassian.com/git/tutorials/merging-vs-rebasing) and distracting you from your work. :laughing: I just want to give you some suggestions how to keep your current feature branch `mbomfim-metascraper-bump` of your [fork](https://github.com/MarcoBomfim/Embed-API) up-to-date with the upstream `master` branch of the [`origin`](https://github.com/Human-Connection/Embed-API) repository.

Just pulling the commits from the origin repository and merging it with your feature branch is fine. As a recent feature, Github has a button to merge the latest changes in. Keeping your feature branch up to date avoids merge conflicts from early on.

**Comment by appinteractive** [comment]
One thing is really important before this feature will be merged, we have to guarantee that the output will stay the same. Otherwise the alpha embeds will brake.

**Comment by roschaefer** [comment]
@appinteractive it's very difficult for @MarcoBomfim to know which output has to stay the same. There are no software-tests :disappointed: could you give some examples what is the expected output for what kind of input? Or maybe you can sketch a workflow how @MarcoBomfim can try it out at https://staging.human-connection.org/auth/login ?

**Comment by appinteractive** [comment]
Sure I can provide some. It was meant to be more of an reminder or note to use Robert. 

You can check the [embed components](https://github.com/Human-Connection/WebApp/tree/develop/modules/quill-url-embeds/components) for the specific fields. 

But for now just go ahead as we need to simply it anyway. But before merge we need to doublecheck and maybe tweak some things.

**Comment by MarcoBomfim** [comment]
@appinteractive, I agree with @roschaefer since I was kind of "blind coding" the output. But Metascraper is ridiculously simple to configure the output, since we can define it as follows: 
```
const metascraper = require('metascraper').load([
  require('metascraper-date')(),
  require('metascraper-title')(),
  require('metascraper-description')(),
  require('metascraper-image')()
]);
```
So far, the output above is the one that is being returned. From what I can see on the Vue code there, once a Youtube link is inserted, it should return a thumbnail for the video, correct? Or is it an little embeded video that is rendered?

**Comment by mbomfim33** [comment]
@appinteractive are we good to close this one? not sure why it is still going, did I forget something?

**Comment by roschaefer** [comment]
@MarcoBomfim both @appinteractive and I are not active in Human-Connection anymore. Yet, I can tell you that this repository has been merged into the backend a long time already. Sb. with admin permissions on the Organization @Human-Connection/hc-team should archive this repository

**Comment by mbomfim33** [comment]
Hey, @roschaefer! Thanks my dude, for a minute there I thought I had forgotten about this PR and people were still waiting on it hehehe

**Pull request closed without merging**
